import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import { Container } from '@mui/material'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <Container>
        <div>
          <h1>Topper Public School</h1>
          <h1>Results</h1>
        </div>
        <div className='flex justify-center items-center'>
          <div className={styles.card}>
            <h1>Divyam Prusty</h1>
          </div>
          <div className={styles.card}>
            <h1>Divyam Prusty</h1>
          </div>
        </div>
      </Container>
    </div>
  )
}
